---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 34174.
--- DateTime: 2024/11/23 16:31
---
---将判断库存是否充足、判断用户是否下单以及扣减库存操作全交给lua脚本，实现原子性操作

---1.参数列表
---1.1优惠卷id
local voucherId=ARGV[1]
---1.2用户id
local userId=ARGV[2]
---1.3订单id
local orderId=ARGV[3]

---2.数据Key
---2.1库存Key
local stockKey='seckill:stock:'..voucherId

---2.2订单key
local orderKey='seckill:order:'..voucherId


---3.脚本业务
---3.1判断库存是否充足 getstockKey
if(tonumber(redis.call('get',stockKey))<=0) then
    --3.2库存不足
    return 1
end

---3.2判断用户是否下单

if(redis.call('sismember',orderKey,userId)==1) then
    --存在，即重复下单
    return 2
end

---3.4扣库存
redis.call('incrby',stockKey,-1)

---3.5下单（保存用户）
redis.call('sadd',orderKey,userId)

---3.6发送消息到队列中，XADD
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)

return 0